name: Build and Test
on: [push, pull_request]
jobs:
  run-dart-api-tests:
    name: Run Dart API tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.5.2"
      - run: |
          flutter test test/mparticle_flutter_sdk_test.dart
  build-android:
    name: Build Android flutter app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.5.2"
      - run: |
          cd example
          flutter pub get
          flutter build apk
          flutter build appbundle
  build-ios:
    name: Build iOS flutter app
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.5.2"
      - run: |
          cd example
          flutter pub get
          flutter build apk
          flutter build ios --release --no-codesign
  build-web:
    name: Build web flutter app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.5.2"
      - run: |
          cd example
          flutter pub get
          flutter build web

# e2e-tests:
#   name: "Run Android E2E tests"
#   timeout-minutes: 30
#   runs-on: macos-11
#   steps:
#     - name: "Checkout Branch"
#       uses: actions/checkout@v2
#     - name: "Install flutter"
#       uses: subosito/flutter-action@v1
#       with:
#         flutter-version: "2.5.2"
#     - name: "Install JDK 11"
#       uses: actions/setup-java@v2
#       with:
#         distribution: "zulu"
#         java-version: "11"
#     - name: "Run Instrumented Tests"
#       uses: reactivecircus/android-emulator-runner@v2.20.0
#       with:
#         api-level: 29
#         script: cd test/e2e_example_app; flutter test integration_test/foo_test.dart

